# fly.toml app configuration file generated for yefim-redirector on 2023-08-03T00:36:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yefim-redirector"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "ord"

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "1m0s"
    grace_period = "1s"
    method = "get"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

  [[services.http_checks]]
    interval = "10s"
    timeout = "1m0s"
    grace_period = "1s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    tls_skip_verify = false
